### ISSUE TITLE
Inadequate performance

### ISSUE THREAD

**Issue by jgriss** [spectra-cluster/spectra-cluster-cli#1]
The performance of this tool is currently inadequate.
@ruiwanguk Any suggestions are highly welcome!

**Comment by ruiwanguk** [comment]
I will see what I can do asap

**Comment by jgriss** [comment]
spectra-cluster/spectra-cluster@869e69968f6a152993ec3a627dd48dd663c7053a fixed performance issues of all probabilistic comparison methods. Now the combined test is only 3x slower than the dot product. Nevertheless, the overall performance of the CLI is still inadequate.

@ruiwanguk Now I need your help

**Comment by ruiwanguk** [comment]
@jgriss Ok, let me take a look

**Comment by jgriss** [comment]
Performance of the latest release [v 1.0 beta](https://github.com/spectra-cluster/spectra-cluster-cli/releases/tag/v1.0-beta) is fine.
