### ISSUE TITLE
measuring metircs

### ISSUE THREAD

**Issue by leiwang-me** [spectra-cluster/spectra-cluster-cli#4]
Hi,

Could you please provide the statistics such as how long it takes for the IO, clustering etc?  I would like to know the time for clustering, but I didn't know how to do it.  

Many thanks!
Lei

**Comment by jgriss** [comment]
Hi Lei,

I am not sure that I fully understand your question: Is this a request for us to add some kind of timer to the tool or do you just want to know how you can time the process yourself?

For the latter, I'd need to know which operating system you are using.

Best regards,
Johannes

**Comment by leiwang-me** [comment]
Hi Johannes,

Thanks for getting back to me that quickly!  I am using Linux and know how to time the process.  Could you provide a new feature to your program which can time every step of the program, such as the time for IO, the time for clustering, etc?

Thanks1
Lei

**Comment by jgriss** [comment]
Unfortunately, adding these metrics are incompatible to some of the designs of the API. Sorry about that!
