### ISSUE TITLE
problems getting started with spectra-cluster-cli

### ISSUE THREAD

**Issue by skeffington** [spectra-cluster/spectra-cluster-cli#8]
Hi,

I'm very interested in using the spectra-cluster-cli tool - I simply want to submit an mgf file and get out clusters, preferable with consensus spectra, which I can then use downstream in a database quality control pipeline for work with non-model organisms.

Unfortunately I'm having trouble getting started. When I download and unzip the tool I first of all get a rather odd directory structure: 
```spectra-cluster-cli-master/src/main/java/uk/ac/ebi/pride/spectracluster``` which contains the following ```binning  cdf  cli  clustering  conversion  implementation  merging  spectra_list  util``` - none of which contain a java application with the stem spectra-cluster-cli* as suggested in the docs.  I tried 
```java -jar SpectraClusterStandalone.java -help``` and 
``` java -jar SpectraClusterCliMain.java -help``` but simply get ```Error: Invalid or corrupt jarfile SpectraClusterStandalone.java```.  I'm running 
```OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10), OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)```

I also tried downloading the Proteome discoverer software in windows, but having downloaded and run the installation of the SpectrumClustering2.1.0.0-setup.exe apparently without errors, I can't see the tool in the spectrum processing tools menu. Perhaps this is a compatibility issue, since I can only download Proteom discoverer v. 2.4.

Is there anything I can do to get this running in a simple way, without having to get our systems administrator involved to try and get the Hardoop version running?

Many thanks!
Alastair

**Comment by jgriss** [comment]
Hi Alastair,

You can find the correct zip file in the [releases](https://github.com/spectra-cluster/spectra-cluster-cli/releases) section. I guess you downloaded the zip file from the "code" page which gives you a zip file of the source code archive. That's not our design but the way GitHub is organised.

The complete link to the correct zip file is: https://github.com/spectra-cluster/spectra-cluster-cli/releases/download/spectra-cluster-cli-1.1.2/spectra-cluster-cli-1.1.2-bin.zip

About the PD installation: The spectra-cluster node only works on PD 2.0, 2.1, 2.3. You can find a tutorial of how to install PD version 2.1 on our Readme page: https://spectra-cluster.github.io/tutorials/proteome_discoverer.html#free-version-of-proteome-discoverer

Kind regards,
Johannes

**Comment by skeffington** [comment]
Hi Johannes,

Many thanks for your help - the correct link works perfectly.

Alastair
